version: '3.8'

services:
  app:
    build: .
    container_name: go-rest-api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./docs:/app/docs
    networks:
      - library-network
    restart: on-failure

  postgres:
    image: postgres:14-alpine
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - library-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  library-network:
    driver: bridge

volumes:
  postgres-data: